version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    depends_on:
      - db
      - alembic
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend_credit_cards
  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
